import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { createApp } from '../server.js';

const directory = await mkdtemp(join(tmpdir(),'mailroom-ui-'));
let providerReady=false,preflightFails=true;
const mockSent=[];
const server = createApp({dataDir:directory,delay:10,dailyLimit:0,auth:{username:'admin',password:'ui-test-password'},transport:() => ({ready:providerReady,name:'Mock SMTP',from:'test@example.com'}),verify:async()=>{if(preflightFails)throw Object.assign(new Error('blocked'),{code:'ETIMEDOUT'});return {verified:true,message:'Mock connection verified. No email sent.'};},sender:async message=>{mockSent.push(message);return {messageId:'mock-'+mockSent.length};}});
server.listen(0,'127.0.0.1'); await once(server,'listening');
let browser;
try {
  browser = await chromium.launch({executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const errors=[]; page.on('pageerror',error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
  await page.getByRole('textbox',{name:'Username',exact:true}).fill('admin');
  await page.getByLabel('Password',{exact:true}).fill('incorrect');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByText('Incorrect username or password.').waitFor();
  await page.getByLabel('Password',{exact:true}).fill('ui-test-password');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('heading',{name:'Good things start with an email.'}).waitFor();
  await mkdir('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Switch to dark mode'}).click();
  await page.reload();
  await page.getByRole('button',{name:'Switch to light mode'}).waitFor();
  await page.screenshot({path:'artifacts/dashboard-dark.png',fullPage:true});
  await page.getByRole('button',{name:'Import contacts',exact:true}).click();
  await page.locator('#import-file').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from('Name,Email,Domain\nAlex Morgan,alex@example.com,Marketing\nJamie Lee,jamie@example.com,Technical\nDuplicate,alex@example.com,Test\nInvalid,not-valid,Test')});
  await page.getByText('2 contacts added',{exact:true}).waitFor();
  await page.getByText('2 rows skipped',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('button',{name:'Create campaign',exact:true}).first().click();
  await page.locator('#compose-name').fill('A new beginning');
  await page.locator('#compose-subject').fill('Welcome, {{name}}');
  await page.locator('#compose-body').fill('Hi {{name}},\nWelcome to the {{domain}} team!');
  await page.getByRole('button',{name:'Choose audience',exact:true}).click();
  await page.locator('#compose-all').check();
  await page.getByRole('button',{name:'Review campaign',exact:true}).click();
  assert.match(await page.locator('.email-preview-body').innerText(),/Hi Alex Morgan/);
  assert.equal(await page.getByRole('button',{name:'Send to 2 people',exact:true}).isDisabled(),true);
  await page.screenshot({path:'artifacts/campaign-preview.png',fullPage:true});
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await page.locator('dialog').waitFor({state:'detached'});
  await page.reload();
  await page.getByRole('button',{name:/A new beginning Welcome/}).waitFor();
  await page.getByRole('button',{name:'Audience',exact:true}).click();
  await page.getByRole('button',{name:'Add contact',exact:true}).click();
  await page.getByRole('textbox',{name:'Full name',exact:true}).fill('Taylor Smith');
  await page.getByRole('textbox',{name:'Email address',exact:true}).fill('taylor@example.com');
  await page.locator('dialog').getByRole('button',{name:'Add contact',exact:true}).click();
  await page.getByText('taylor@example.com',{exact:true}).waitFor();
  await page.getByRole('textbox',{name:'Search contacts'}).fill('Jamie');
  assert.equal(await page.locator('tbody tr').count(),1);
  await page.getByRole('textbox',{name:'Search contacts'}).fill('');
  await page.getByRole('checkbox',{name:'Select Taylor Smith',exact:true}).check();
  await page.getByRole('button',{name:'Remove 1',exact:true}).click();
  await page.getByRole('button',{name:'Remove contacts',exact:true}).click();
  await page.getByText('taylor@example.com',{exact:true}).waitFor({state:'detached'});
  await page.getByRole('button',{name:'Templates',exact:true}).click();
  await page.getByRole('button',{name:/Onboarding A warm welcome/}).click();
  assert.match(await page.locator('#compose-body').inputValue(),/so glad you’re here/);
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('heading',{name:'Email connection',exact:true}).waitFor();
  providerReady=true;
  await page.getByRole('button',{name:'Test connection',exact:true}).click();
  await page.locator('.settings-content .warning-note').waitFor();
  assert.equal(mockSent.length,0);
  preflightFails=false;
  await page.getByRole('button',{name:'Test connection',exact:true}).click();
  await page.getByText('Connection verified',{exact:true}).waitFor();
  await page.getByRole('button',{name:/^Campaigns/}).click();
  await page.getByRole('button',{name:/A new beginning Welcome/}).click();
  await page.getByRole('button',{name:'3 Review & send',exact:true}).click();
  preflightFails=true;
  await page.getByRole('button',{name:'Send to 2 people',exact:true}).click();
  await page.locator('.badge.paused').waitFor();
  await page.getByRole('button',{name:/A new beginning Welcome/}).click();
  await page.getByRole('button',{name:'Resume 2 unsent',exact:true}).waitFor();
  await page.screenshot({path:'artifacts/campaign-paused.png',fullPage:true});
  await page.getByRole('button',{name:'Resume 2 unsent',exact:true}).click();
  preflightFails=false;
  await page.getByRole('button',{name:'Confirm resume',exact:true}).click();
  await page.locator('.badge.sent').waitFor();
  assert.equal(mockSent.length,2);
  assert.equal(new Set(mockSent.map(m=>m.to)).size,2);
  await page.getByRole('button',{name:'Create campaign',exact:true}).first().click();
  await page.locator('#compose-name').fill('HTML invitation');
  await page.locator('#compose-subject').fill('Hello {{name}}');
  const html='<html><head><style>h1{color:#7953cf}td{padding:20px}</style></head><body><table width="100%"><tr><td><h1>Hello {{name}}</h1><p>Welcome to our new team. Your next steps are ready.</p><a href="https://example.com">Read the details</a></td></tr></table><script>window.parent.htmlInjected=true</script></body></html>';
  await page.locator('#html-file').setInputFiles({name:'invitation.html',mimeType:'text/html',buffer:Buffer.from(html)});
  await page.frameLocator('.html-email-frame').getByRole('heading',{name:'Hello Alex',exact:true}).waitFor();
  assert.equal(await page.locator('#compose-body').inputValue(),html);
  assert.equal(await page.evaluate(()=>window.htmlInjected),undefined);
  assert.equal(await page.locator('.html-email-frame').getAttribute('sandbox'),'');
  await page.getByRole('button',{name:'Plain text',exact:true}).click();
  await page.locator('#compose-body').fill('Preserved plain draft');
  await page.getByRole('button',{name:'HTML',exact:true}).click();
  assert.equal(await page.locator('#compose-body').inputValue(),html);
  await page.locator('#compose-body').fill(html.replace('Welcome to our new team.','Glad you are here.'));
  await page.locator('#compose-kind').selectOption('marketing');
  await page.frameLocator('.html-email-frame').getByRole('link',{name:'Unsubscribe from marketing emails'}).waitFor();
  await page.getByRole('button',{name:'Choose audience',exact:true}).click();
  await page.locator('#compose-all').check();
  await page.getByRole('button',{name:'Review campaign',exact:true}).click();
  await page.frameLocator('.html-email-frame').getByRole('heading',{name:'Hello Alex Morgan',exact:true}).waitFor();
  await page.screenshot({path:'artifacts/html-review-dark.png',fullPage:true});
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await page.getByRole('button',{name:/HTML invitation Hello/}).click();
  assert.match(await page.locator('#compose-body').inputValue(),/Glad you are here/);
  await page.setViewportSize({width:390,height:844});
  await page.frameLocator('.html-email-frame').getByRole('heading',{name:'Hello Alex Morgan',exact:true}).waitFor();
  await page.screenshot({path:'artifacts/html-editor-mobile.png',fullPage:true});
  assert.equal(await page.locator('dialog').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);
  await page.setViewportSize({width:1440,height:1080});
  await page.getByRole('button',{name:'3 Review & send',exact:true}).click();
  await page.getByRole('button',{name:'Send to 2 people',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('tbody .badge.sent').length===2);
  assert.equal(mockSent.length,4);
  assert.match(mockSent[2].html,/color: *#7953cf/);
  assert.match(mockSent[2].text,/Glad you are here/);
  assert.ok(mockSent[2].headers['List-Unsubscribe'].startsWith('<mailto:'));
  assert.doesNotMatch(mockSent[2].html,/<script/);
  await page.getByRole('button',{name:'Audience',exact:true}).click();
  await page.getByRole('checkbox',{name:'Select Jamie Lee',exact:true}).check();
  await page.getByRole('button',{name:'Unsubscribe 1',exact:true}).click();
  await page.getByRole('button',{name:'Confirm unsubscribe',exact:true}).click();
  await page.getByText('Unsubscribed · excluded from sends',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Overview',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/dashboard-mobile.png',fullPage:true});
  const overflow = await page.evaluate(() => ({width:window.innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(e => e.getBoundingClientRect().right > window.innerWidth + 1 && getComputedStyle(e).position === 'absolute').map(e => ({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right}))}));
  assert.equal(overflow.scroll > overflow.width,false,JSON.stringify(overflow));
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('button',{name:'Audience',exact:true}).click();
  await page.getByRole('heading',{name:'Good people. One place.'}).waitFor();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
  await page.reload();
  await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
  await page.screenshot({path:'artifacts/login-dark-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1080});
  await page.screenshot({path:'artifacts/login-dark.png',fullPage:true});
  await page.getByRole('button',{name:'Switch to light mode'}).click();
  await page.screenshot({path:'artifacts/login-light.png',fullPage:true});
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('UI checks passed: imports, previews, drafts, contacts, templates, connection diagnostics, paused campaigns, resume, simulated bulk sends, dark mode, login/logout, mobile navigation, and no browser errors.');
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
  await rm(directory,{recursive:true,force:true});
}
